#!/usr/bin/env python
"""Generate bundled species assets for the standalone SPA build.

Runs from the repo root. Uses backend.config_io.load_stac_yaml to convert
each species' upstream stac-mjx YAML into the JSON shape the frontend
expects, and copies the XML next to it. Only species whose XMLs have no
external mesh asset deps are bundled — others stay backend-only until a
mesh-stripping preprocessor lands.

Currently bundled:
  - rat (rodent_relaxed.xml + ACM demo data, generated by precompute_assets.py)
  - stick (sungaya_inexpectata_box.xml + config from sungaya_inexpectata.yaml)

Skipped (mesh-asset deps; backend-only for now):
  - worm  (celegans.xml: 25 mesh refs)
  - fly   (fruitfly_force.xml: many mesh refs)
  - mouse (mouse_with_meshes.xml: 200+ mesh refs)
"""
from __future__ import annotations
import json
import shutil
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from backend.config_io import load_stac_yaml  # noqa: E402

OUT = REPO_ROOT / "frontend" / "public" / "data"
OUT.mkdir(parents=True, exist_ok=True)


def export_species(name: str, xml_src: Path, yaml_src: Path | None) -> None:
    species_dir = OUT / name
    species_dir.mkdir(exist_ok=True)

    xml_dst = species_dir / xml_src.name
    shutil.copy2(xml_src, xml_dst)
    print(f"  XML: {xml_src.name} -> {xml_dst.relative_to(REPO_ROOT)}")

    if yaml_src is None:
        print("  (no default config — researchers upload their own)")
        return

    loaded = load_stac_yaml(str(yaml_src))
    config_json = {
        "keypointModelPairs": dict(loaded["keypointModelPairs"]),
        "keypointInitialOffsets": loaded["keypointInitialOffsets"],
        "scaleFactor": float(loaded["scaleFactor"]),
        "mocapScaleFactor": float(loaded["mocapScaleFactor"]),
        "kpNames": list(loaded["kpNames"]),
    }
    cfg_dst = species_dir / "stac_config.json"
    cfg_dst.write_text(json.dumps(config_json, indent=2))
    print(f"  Config: {len(config_json['kpNames'])} kps -> {cfg_dst.relative_to(REPO_ROOT)}")


def main() -> None:
    # Stick — clean XML, default config from the handoff package.
    handoff = REPO_ROOT.parent / "stick_handoff" / "data"
    export_species(
        "stick",
        xml_src=handoff / "sungaya_inexpectata_box.xml",
        yaml_src=handoff / "sungaya_inexpectata.yaml",
    )
    print("Done.")


if __name__ == "__main__":
    main()
